# Render.com monorepo deployment for frontend (Vite) and backend (Node.js)

services:
  - type: web
    name: hardbanrecords-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_REGION
        sync: false
      - key: SUPABASE_BUCKET_NAME
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
    autoDeploy: true
    rootDir: backend

  - type: web
    name: hardbanrecords-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: VITE_API_URL
        sync: false
    autoDeploy: true
    rootDir: .
