# Render.com backend service definition for Node.js Express
services:
  - type: web
    name: hardbanrecords-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
    autoDeploy: true
    rootDir: backend
